# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 23:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='descr',
            field=models.CharField(default=datetime.datetime(2016, 5, 8, 23, 53, 16, 298399, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
