# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 15:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_course_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='url',
        ),
        migrations.AddField(
            model_name='lesson',
            name='body',
            field=models.TextField(default=datetime.datetime(2016, 5, 15, 15, 46, 48, 407876, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
