# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20160515_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='descr',
            field=models.CharField(default='Nothing', max_length=420),
            preserve_default=False,
        ),
    ]
