# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_lesson_descr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='descr',
            field=models.CharField(max_length=420, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='views',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
