# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, default='All null', upload_to=''),
            preserve_default=False,
        ),
    ]
