# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 00:40
from __future__ import unicode_literals

from django.db import migrations
from django.db import models

def add_group_permissions():
    #read_only
    group, created = Group.objects.get_or_create(name='Máquinas de Fluxo')   

    #standard
    group, created = Group.objects.get_or_create(name='Mecânica dos Fluidos 2') 

    #admin
    group, created = Group.objects.get_or_create(name='Sistemas 3') 

class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_student'),
    ]

    operations = [
    ]
