# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_mymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='nick',
            field=models.CharField(blank=True, default=uuid.uuid1, error_messages={'unique': 'That address has already been added.'}, max_length=7, null=True),
        ),
    ]
